# -*- coding: utf-8 -*-
import json
from pathlib import Path

out = Path(__file__).resolve().parent / "messages.json"

messages = {
    "fr": {
        "Title": "SynapticRemover - Outil Complet XRed / Synaptics Backdoor",
        "NeedAdmin": "Ce script doit etre lance en tant qu'Administrateur.",
        "NeedAdminHint": "Clic droit > Executer en tant qu'administrateur",
        "Intro1": "Nettoyage persistance + dossiers + caches + USB",
        "Intro2": "+ synaptics-recover (kill + reparation EXE/XLSM)",
        "Sources": "Sources :",
        "PressKey": "Appuyez sur une touche pour continuer...",
        "Step": "ETAPE",
        "Step1": "Afficher les fichiers caches",
        "Step1Ok": "Fichiers caches visibles (Hidden + SuperHidden)",
        "Step2": "Arreter les processus malveillants",
        "ProcKilled": "Processus Synaptics.exe arrete",
        "ProcKillFail": "Impossible de tuer Synaptics.exe",
        "ProcKilledPid": "Processus tue : {0} (PID {1})",
        "ProcNone": "Aucun processus Synaptics detecte",
        "Step3": "Nettoyer la persistance registre",
        "RegRemoved": "Supprime : {0}\\{1}",
        "RegFail": "Echec suppression : {0}\\{1}",
        "RegNone": "Aucune cle de demarrage Synaptics trouvee",
        "Step4": "Supprimer les dossiers virus",
        "DirRemoved": "Supprime : {0}",
        "DirFail": "Echec suppression : {0}",
        "DirMissing": "Introuvable : {0}",
        "Step5": "Supprimer caches virus (._cache_* / ~$cache1)",
        "Step5Warn": "Scan caches termine avec avertissements",
        "Step6": "Scanner les cles USB (autorun / Synaptics)",
        "Step6Warn": "Scan USB termine avec avertissements",
        "Step7": "Nettoyer %TEMP%",
        "TempTarget": "Cible : {0}",
        "TempOk": "Nettoyage TEMP termine (fichiers verrouilles ignores)",
        "Step8": "Preparer synaptics-recover",
        "ToolDownloading": "Binary absent - tentative de telechargement...",
        "ToolReady": "Binary pret : {0}",
        "ToolMissing": "synaptics-recover introuvable - etapes 9-10 ignorees",
        "Step9": "Kill mode synaptics-recover (-k)",
        "ToolLaunch": "Lancement : {0} -k",
        "KillFail": "synaptics-recover -k a renvoye une erreur",
        "KillOk": "Kill mode termine",
        "StepSkipped": "Etape ignoree (outil absent)",
        "Step10": "Scan / reparation EXE et XLSM",
        "ScanIntro1": "Cette etape utilise synaptics-recover pour reparer les fichiers",
        "ScanIntro2": "infectes (EXE encapsules + XLSM -> XLSX). Peut etre long.",
        "ScanOpt1": "[1] Profil utilisateur seulement  ({0})",
        "ScanOpt2": "[2] Disque systeme complet        ({0}\\)  [LONG]",
        "ScanOpt3": "[3] Ignorer le scan profond",
        "ScanPrompt": "Choix [1/2/3] : ",
        "ScanSkipped": "Scan profond ignore",
        "ScanNoTool": "Impossible de scanner : outil absent",
        "ScanRunning": "Scan en cours : {0}",
        "ScanDontClose": "Ne fermez pas cette fenetre...",
        "ScanWarn": "Scan termine avec erreurs / avertissements",
        "ScanOk": "Scan / reparation termine",
        "Step11": "Verification finale",
        "DoneTitle": "NETTOYAGE TERMINE",
        "HashRef": "Hash reference (guide d5-i) :",
        "Credits": "Credits :",
        "TracesRemain": "Des traces peuvent rester - redemarrez puis relancez",
        "NoTraces": "Aucune trace evidente restante",
        "RebootPrompt": "Redemarrer l'ordinateur maintenant ? [O]=Oui  [N]=Non : ",
        "RebootYesKeys": "ON",
        "RebootIn10": "Redemarrage dans 10 secondes... (Ctrl+C pour annuler)",
        "RebootCancel": "Redemarrage annule. Pensez a redemarrer plus tard.",
        "RebootMsg": "SynapticRemover - redemarrage demande par l'utilisateur",
        "BannerSub": "R E M O V E R   -   OUTIL COMPLET",
        "AskingAdmin": "Demande des droits Administrateur...",
        "H_ToolPresent": "Outil present : {0}",
        "H_Downloading": "Telechargement de synaptics-recover 0.0.1.6...",
        "H_DlFail": "Echec telechargement : {0}",
        "H_Downloaded": "Telecharge : {0}",
        "H_BinMissing": "Binary introuvable apres extraction",
        "H_CacheSearch": "Recherche rapide de ._cache_* et ~$cache1 (progression affichee)...",
        "H_Found": "Trouve : {0}",
        "H_Deleted": "Supprime : {0}",
        "H_DelFail": "Echec suppression : {0}",
        "H_CacheSummary": "Caches : {0} trouve(s), {1} supprime(s)",
        "H_UsbScan": "Scan des lecteurs amovibles (autorun.inf / Synaptics)...",
        "H_NoUsb": "Aucun lecteur amovible detecte",
        "H_Drive": "Lecteur {0}",
        "H_AutorunBad": "autorun.inf suspect : {0}",
        "H_AutorunOk": "autorun.inf present mais sans marqueur Synaptics (laisse tel quel)",
        "H_UsbDir": "Dossier Synaptics sur USB : {0}",
        "H_UsbFile": "Fichier suspect USB : {0}",
        "H_Fail": "Echec : {0}",
        "H_StillPresent": "Encore present : {0}",
        "H_ProcAlive": "Processus Synaptics encore actif",
        "H_RegLeft": "Cle registre restante : {0}\\{1}",
        "H_VerifyOk": "Verification : aucune trace evidente restante",
        "H_VerifyWarn": "Verification : {0} trace(s) restante(s)",
    },
    "en": {
        "Title": "SynapticRemover - Complete Tool XRed / Synaptics Backdoor",
        "NeedAdmin": "This script must be run as Administrator.",
        "NeedAdminHint": "Right-click > Run as administrator",
        "Intro1": "Cleanup: persistence + folders + caches + USB",
        "Intro2": "+ synaptics-recover (kill + EXE/XLSM repair)",
        "Sources": "Sources:",
        "PressKey": "Press any key to continue...",
        "Step": "STEP",
        "Step1": "Show hidden files",
        "Step1Ok": "Hidden files visible (Hidden + SuperHidden)",
        "Step2": "Stop malicious processes",
        "ProcKilled": "Synaptics.exe process stopped",
        "ProcKillFail": "Could not kill Synaptics.exe",
        "ProcKilledPid": "Process killed: {0} (PID {1})",
        "ProcNone": "No Synaptics process detected",
        "Step3": "Clean registry persistence",
        "RegRemoved": "Removed: {0}\\{1}",
        "RegFail": "Failed to remove: {0}\\{1}",
        "RegNone": "No Synaptics startup key found",
        "Step4": "Remove virus folders",
        "DirRemoved": "Removed: {0}",
        "DirFail": "Failed to remove: {0}",
        "DirMissing": "Not found: {0}",
        "Step5": "Remove virus caches (._cache_* / ~$cache1)",
        "Step5Warn": "Cache scan finished with warnings",
        "Step6": "Scan USB drives (autorun / Synaptics)",
        "Step6Warn": "USB scan finished with warnings",
        "Step7": "Clean %TEMP%",
        "TempTarget": "Target: {0}",
        "TempOk": "TEMP cleanup done (locked files ignored)",
        "Step8": "Prepare synaptics-recover",
        "ToolDownloading": "Binary missing - attempting download...",
        "ToolReady": "Binary ready: {0}",
        "ToolMissing": "synaptics-recover not found - steps 9-10 skipped",
        "Step9": "Kill mode synaptics-recover (-k)",
        "ToolLaunch": "Running: {0} -k",
        "KillFail": "synaptics-recover -k returned an error",
        "KillOk": "Kill mode finished",
        "StepSkipped": "Step skipped (tool missing)",
        "Step10": "Scan / repair EXE and XLSM",
        "ScanIntro1": "This step uses synaptics-recover to repair infected",
        "ScanIntro2": "files (wrapped EXE + XLSM -> XLSX). May take a while.",
        "ScanOpt1": "[1] User profile only           ({0})",
        "ScanOpt2": "[2] Full system drive           ({0}\\)  [LONG]",
        "ScanOpt3": "[3] Skip deep scan",
        "ScanPrompt": "Choice [1/2/3]: ",
        "ScanSkipped": "Deep scan skipped",
        "ScanNoTool": "Cannot scan: tool missing",
        "ScanRunning": "Scanning: {0}",
        "ScanDontClose": "Do not close this window...",
        "ScanWarn": "Scan finished with errors / warnings",
        "ScanOk": "Scan / repair finished",
        "Step11": "Final verification",
        "DoneTitle": "CLEANUP FINISHED",
        "HashRef": "Reference hash (d5-i guide):",
        "Credits": "Credits:",
        "TracesRemain": "Traces may remain - reboot then run again",
        "NoTraces": "No obvious traces remaining",
        "RebootPrompt": "Restart the computer now? [Y]=Yes  [N]=No: ",
        "RebootYesKeys": "YN",
        "RebootIn10": "Restarting in 10 seconds... (Ctrl+C to cancel)",
        "RebootCancel": "Restart cancelled. Please reboot later.",
        "RebootMsg": "SynapticRemover - restart requested by user",
        "BannerSub": "R E M O V E R   -   COMPLETE TOOL",
        "AskingAdmin": "Requesting Administrator rights...",
        "H_ToolPresent": "Tool present: {0}",
        "H_Downloading": "Downloading synaptics-recover 0.0.1.6...",
        "H_DlFail": "Download failed: {0}",
        "H_Downloaded": "Downloaded: {0}",
        "H_BinMissing": "Binary not found after extraction",
        "H_CacheSearch": "Quick search for ._cache_* and ~$cache1 (progress shown)...",
        "H_Found": "Found: {0}",
        "H_Deleted": "Deleted: {0}",
        "H_DelFail": "Failed to delete: {0}",
        "H_CacheSummary": "Caches: {0} found, {1} deleted",
        "H_UsbScan": "Scanning removable drives (autorun.inf / Synaptics)...",
        "H_NoUsb": "No removable drive detected",
        "H_Drive": "Drive {0}",
        "H_AutorunBad": "Suspicious autorun.inf: {0}",
        "H_AutorunOk": "autorun.inf present but no Synaptics marker (left as-is)",
        "H_UsbDir": "Synaptics folder on USB: {0}",
        "H_UsbFile": "Suspicious USB file: {0}",
        "H_Fail": "Failed: {0}",
        "H_StillPresent": "Still present: {0}",
        "H_ProcAlive": "Synaptics process still running",
        "H_RegLeft": "Registry key remaining: {0}\\{1}",
        "H_VerifyOk": "Verify: no obvious traces remaining",
        "H_VerifyWarn": "Verify: {0} remaining trace(s)",
    },
    "ar": {
        "Title": "SynapticRemover - أداة كاملة XRed / Synaptics Backdoor",
        "NeedAdmin": "يجب تشغيل هذا البرنامج كمسؤول.",
        "NeedAdminHint": "انقر بزر الماوس الأيمن > تشغيل كمسؤول",
        "Intro1": "تنظيف: الاستمرارية + المجلدات + الذاكرة المؤقتة + USB",
        "Intro2": "+ synaptics-recover (إيقاف + إصلاح EXE/XLSM)",
        "Sources": "المصادر:",
        "PressKey": "اضغط أي مفتاح للمتابعة...",
        "Step": "خطوة",
        "Step1": "إظهار الملفات المخفية",
        "Step1Ok": "الملفات المخفية ظاهرة (Hidden + SuperHidden)",
        "Step2": "إيقاف العمليات الضارة",
        "ProcKilled": "تم إيقاف عملية Synaptics.exe",
        "ProcKillFail": "تعذر إنهاء Synaptics.exe",
        "ProcKilledPid": "تم إنهاء العملية: {0} (PID {1})",
        "ProcNone": "لم يتم اكتشاف عملية Synaptics",
        "Step3": "تنظيف استمرارية السجل",
        "RegRemoved": "تم الحذف: {0}\\{1}",
        "RegFail": "فشل الحذف: {0}\\{1}",
        "RegNone": "لم يتم العثور على مفتاح بدء Synaptics",
        "Step4": "حذف مجلدات الفيروس",
        "DirRemoved": "تم الحذف: {0}",
        "DirFail": "فشل الحذف: {0}",
        "DirMissing": "غير موجود: {0}",
        "Step5": "حذف ذاكرة الفيروس المؤقتة (._cache_* / ~$cache1)",
        "Step5Warn": "انتهى فحص الذاكرة المؤقتة مع تحذيرات",
        "Step6": "فحص محركات USB (autorun / Synaptics)",
        "Step6Warn": "انتهى فحص USB مع تحذيرات",
        "Step7": "تنظيف %TEMP%",
        "TempTarget": "الهدف: {0}",
        "TempOk": "تم تنظيف TEMP (تم تجاهل الملفات المقفلة)",
        "Step8": "تجهيز synaptics-recover",
        "ToolDownloading": "الملف غير موجود - محاولة التنزيل...",
        "ToolReady": "الأداة جاهزة: {0}",
        "ToolMissing": "synaptics-recover غير موجود - تخطي الخطوتين 9-10",
        "Step9": "وضع الإيقاف synaptics-recover (-k)",
        "ToolLaunch": "تشغيل: {0} -k",
        "KillFail": "أرجع synaptics-recover -k خطأ",
        "KillOk": "انتهى وضع الإيقاف",
        "StepSkipped": "تم تخطي الخطوة (الأداة غير موجودة)",
        "Step10": "فحص / إصلاح EXE و XLSM",
        "ScanIntro1": "تستخدم هذه الخطوة synaptics-recover لإصلاح الملفات",
        "ScanIntro2": "المصابة (EXE مغلف + XLSM -> XLSX). قد يستغرق وقتا.",
        "ScanOpt1": "[1] ملف المستخدم فقط              ({0})",
        "ScanOpt2": "[2] قرص النظام بالكامل            ({0}\\)  [طويل]",
        "ScanOpt3": "[3] تخطي الفحص العميق",
        "ScanPrompt": "الاختيار [1/2/3]: ",
        "ScanSkipped": "تم تخطي الفحص العميق",
        "ScanNoTool": "تعذر الفحص: الأداة غير موجودة",
        "ScanRunning": "جاري الفحص: {0}",
        "ScanDontClose": "لا تغلق هذه النافذة...",
        "ScanWarn": "انتهى الفحص مع أخطاء / تحذيرات",
        "ScanOk": "انتهى الفحص / الإصلاح",
        "Step11": "التحقق النهائي",
        "DoneTitle": "انتهى التنظيف",
        "HashRef": "الهاش المرجعي (دليل d5-i):",
        "Credits": "الشكر:",
        "TracesRemain": "قد تبقى آثار - أعد تشغيل الجهاز ثم شغل الأداة مجددا",
        "NoTraces": "لا توجد آثار واضحة متبقية",
        "RebootPrompt": "إعادة تشغيل الجهاز الآن؟ [Y]=نعم  [N]=لا: ",
        "RebootYesKeys": "YN",
        "RebootIn10": "إعادة التشغيل خلال 10 ثوان... (Ctrl+C للإلغاء)",
        "RebootCancel": "تم إلغاء إعادة التشغيل. يرجى إعادة التشغيل لاحقا.",
        "RebootMsg": "SynapticRemover - طلب المستخدم إعادة التشغيل",
        "BannerSub": "R E M O V E R   -   أداة كاملة",
        "AskingAdmin": "طلب صلاحيات المسؤول...",
        "H_ToolPresent": "الأداة موجودة: {0}",
        "H_Downloading": "جاري تنزيل synaptics-recover 0.0.1.6...",
        "H_DlFail": "فشل التنزيل: {0}",
        "H_Downloaded": "تم التنزيل: {0}",
        "H_BinMissing": "الملف التنفيذي غير موجود بعد الاستخراج",
        "H_CacheSearch": "بحث سريع عن ._cache_* و ~$cache1 (يتم عرض التقدم)...",
        "H_Found": "تم العثور: {0}",
        "H_Deleted": "تم الحذف: {0}",
        "H_DelFail": "فشل الحذف: {0}",
        "H_CacheSummary": "الذاكرة المؤقتة: {0} موجود، {1} محذوف",
        "H_UsbScan": "فحص المحركات القابلة للإزالة (autorun.inf / Synaptics)...",
        "H_NoUsb": "لم يتم اكتشاف محرك قابل للإزالة",
        "H_Drive": "المحرك {0}",
        "H_AutorunBad": "autorun.inf مشبوه: {0}",
        "H_AutorunOk": "autorun.inf موجود بدون علامة Synaptics (ترك كما هو)",
        "H_UsbDir": "مجلد Synaptics على USB: {0}",
        "H_UsbFile": "ملف USB مشبوه: {0}",
        "H_Fail": "فشل: {0}",
        "H_StillPresent": "ما زال موجودا: {0}",
        "H_ProcAlive": "عملية Synaptics ما زالت نشطة",
        "H_RegLeft": "مفتاح سجل متبق: {0}\\{1}",
        "H_VerifyOk": "التحقق: لا توجد آثار واضحة متبقية",
        "H_VerifyWarn": "التحقق: {0} أثر/آثار متبقية",
    },
}

out.write_text(json.dumps(messages, ensure_ascii=False, indent=2), encoding="utf-8-sig")
print(f"Wrote {out}")
